baseURL = "https://integral-dragon.github.io/"
languageCode = "en-us"
title = "Integral Dragon"
themesDir = "../Template"
theme = "gohugo-theme-ananke"
enableRobotsTXT = true

[pagination]
  pagerSize = 10

[params]
  site_logo = "images/ID small logo.png"

[[menus.main]]
  name = "Home"
  url = "/"
  weight = 10

[[menus.main]]
  name = "White Papers"
  url = "/whitepapers/"
  weight = 50

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
